/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Staff;
import controller.controller;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Samreen Gul
 */
public class Reports extends javax.swing.JFrame {
   
    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BAPERS = new javax.swing.JLabel();
        ReportsLabel = new javax.swing.JLabel();
        IndividualJobReportsButton = new javax.swing.JButton();
        PerformanceReportsButton = new javax.swing.JButton();
        SummaryPerformanceReportsButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BAPERS.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BAPERS.setText("BAPERS");

        ReportsLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        ReportsLabel.setText("Reports");

        IndividualJobReportsButton.setBackground(new java.awt.Color(204, 255, 255));
        IndividualJobReportsButton.setText("Individual Job Reports");
        IndividualJobReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndividualJobReportsButtonActionPerformed(evt);
            }
        });

        PerformanceReportsButton.setBackground(new java.awt.Color(204, 255, 255));
        PerformanceReportsButton.setText("Performance Reports");
        PerformanceReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerformanceReportsButtonActionPerformed(evt);
            }
        });

        SummaryPerformanceReportsButton.setBackground(new java.awt.Color(204, 255, 255));
        SummaryPerformanceReportsButton.setText("Summary Performance Reports");
        SummaryPerformanceReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryPerformanceReportsButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Pick Report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BAPERS)
                        .addGap(26, 26, 26)
                        .addComponent(ReportsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IndividualJobReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PerformanceReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SummaryPerformanceReportsButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAPERS)
                    .addComponent(ReportsLabel))
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerformanceReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IndividualJobReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SummaryPerformanceReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IndividualJobReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndividualJobReportsButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewIndividualReport v = new ViewIndividualReport();
        v.setVisible(true);  
    }//GEN-LAST:event_IndividualJobReportsButtonActionPerformed

    private void SummaryPerformanceReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryPerformanceReportsButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewSummaryPerformanceReport v = new ViewSummaryPerformanceReport();
        v.setVisible(true);
        
    }//GEN-LAST:event_SummaryPerformanceReportsButtonActionPerformed

    private void PerformanceReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerformanceReportsButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewIndividualCustSalesReport v = new ViewIndividualCustSalesReport();
        v.setVisible(true);
    }//GEN-LAST:event_PerformanceReportsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Staff st = controller.getSt();
   if(st.getJobTitle().equals("Office Manager") ){
       this.dispose();
       controller.openOfficeMgrHome();//opens the home page for office manager
   } else if(st.getJobTitle().equals("Shift Manager")){
       this.dispose();
       controller.openShiftMgrHome();       
   }else if(st.getJobTitle().equals("Development Technician")){
       this.dispose();
       controller.openTechnicianHome();       
   }else if(st.getJobTitle().equals("CopyRoom Technician")){
       this.dispose();
       controller.openTechnicianHome();       
   }else if(st.getJobTitle().equals("PackingRoom Technician")){
       this.dispose();
       controller.openTechnicianHome();       
   }else if(st.getJobTitle().equals("FinishingRoom Technician")){
       this.dispose();
       controller.openTechnicianHome();       
   }else if(st.getJobTitle().equals("Receptionist")){
       this.dispose();
       controller.openRepHome();
   }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BAPERS;
    private javax.swing.JButton IndividualJobReportsButton;
    private javax.swing.JButton PerformanceReportsButton;
    private javax.swing.JLabel ReportsLabel;
    private javax.swing.JButton SummaryPerformanceReportsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
