/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author sajawal
 */
public class ShiftMgrHome extends javax.swing.JFrame {
    public String name;
    public String role;
    /**
     * Creates new form ShiftMgrHome
     */
    public ShiftMgrHome() {
        initComponents();
    }
    //////////////////////////////////////////////////
//    public class Home extends javax.swing.JFrame {
//    public String name;
//    public String role;
//    
//     (String name, String role)
//        
//        RoleLabel.setText("name: "+name+"   Role: "+role);
//        CurrentUser labelText;
//        this.name=name;
//        this.role=role;
//        try
//        {
//        checkIfXhoursApart();
//        }
//        catch(SQLException ex)
//        { }
//        if ("Technician".equals(role)){
//            BackupButton.setVisible(false);
//            CustomerListButton.setVisible(false);
//            CustomerManagementButton.setVisible(false);
//            PaymentsButton.setVisible(false);
//            PerformanceSummaryButton.setVisible(false);
//            StaffManagementButton.setVisible(false);
//        }
//        else if("Receptionist".equals(role)){
//            BackupButton.setVisible(false);
//            PerformanceSummaryButton.setVisible(false);
//            StaffManagementButton.setVisible(false);
//        }
//        
//        else if("Shift Manager".equals(role)){
//            BackupButton.setVisible(false);
//            PaymentsButton.setVisible(false);            
//        }
    
    ///////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BAPERS = new javax.swing.JLabel();
        SHIFTMANAGER = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        customerAccount = new javax.swing.JButton();
        reports1 = new javax.swing.JButton();
        jobs1 = new javax.swing.JButton();
        createStaffAcc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BAPERS.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BAPERS.setText("BAPERS");

        SHIFTMANAGER.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        SHIFTMANAGER.setText("Shift Manager");

        logout.setBackground(new java.awt.Color(204, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        customerAccount.setBackground(new java.awt.Color(204, 255, 255));
        customerAccount.setText("Customer Acccount");
        customerAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAccountActionPerformed(evt);
            }
        });

        reports1.setBackground(new java.awt.Color(204, 255, 255));
        reports1.setText("Reports");
        reports1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reports1ActionPerformed(evt);
            }
        });

        jobs1.setBackground(new java.awt.Color(204, 255, 255));
        jobs1.setText("Jobs");
        jobs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobs1ActionPerformed(evt);
            }
        });

        createStaffAcc.setBackground(new java.awt.Color(204, 255, 255));
        createStaffAcc.setText("Staff Account");
        createStaffAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStaffAccActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Shift Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BAPERS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SHIFTMANAGER, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(customerAccount)
                                .addGap(95, 95, 95)
                                .addComponent(jobs1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(createStaffAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(reports1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAPERS)
                    .addComponent(SHIFTMANAGER))
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobs1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createStaffAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reports1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
            // TODO add your handling code here:
            this.dispose();
            login log = new login();
            log.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void customerAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAccountActionPerformed
        // TODO add your handling code here:
        CustomerNavGUI ca = new CustomerNavGUI();
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerAccountActionPerformed

    private void reports1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reports1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Reports v = new Reports();
        v.setVisible(true);

    }//GEN-LAST:event_reports1ActionPerformed

    private void jobs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobs1ActionPerformed
        // TODO add your handling code here:
        Jobs j = new Jobs();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jobs1ActionPerformed

    private void createStaffAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStaffAccActionPerformed
        StaffAccountNavGUI csa = new StaffAccountNavGUI();
        csa.setVisible(true);// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_createStaffAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftMgrHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftMgrHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftMgrHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftMgrHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShiftMgrHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BAPERS;
    private javax.swing.JLabel SHIFTMANAGER;
    private javax.swing.JButton createStaffAcc;
    private javax.swing.JButton customerAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jobs1;
    private javax.swing.JButton logout;
    private javax.swing.JButton reports1;
    // End of variables declaration//GEN-END:variables
}
