/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controller.controller;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Samreen Gul
 */
public class ViewCustomerAccountReceptionist extends javax.swing.JFrame {

    /**
     * Creates new form ViewCustomerAccountReceptionist
     */
    public ViewCustomerAccountReceptionist() {
        initComponents();
    }
    public void fetchAllCust() {
        custTable.setModel(DbUtils.resultSetToTableModel(controller.displayAllCust())); // this line displays the mysql database into a GUI
    }
    public void fetchSomeCust() {
    String v = "";
         if (vc.isSelected()){
            v = "YES";
        }else if (nc.isSelected()){
            v = "NO";
        }
        custTable.setModel(DbUtils.resultSetToTableModel(controller.displaySomeCust(v))); // this line displays the mysql database into a GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        CustomerAccountLabel = new javax.swing.JLabel();
        BAPERS = new javax.swing.JLabel();
        UpdateAccountLabel = new javax.swing.JLabel();
        JobsLabel = new javax.swing.JLabel();
        BAPERS1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        custTable = new javax.swing.JTable();
        ViewJobButton = new javax.swing.JButton();
        FindJobLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        vc = new javax.swing.JRadioButton();
        nc = new javax.swing.JRadioButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomerAccountLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        CustomerAccountLabel.setText("Customer Account");

        BAPERS.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BAPERS.setText("BAPERS");

        UpdateAccountLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        UpdateAccountLabel.setText("Find/Search Customer Account");

        JobsLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        JobsLabel.setText("Jobs");

        BAPERS1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BAPERS1.setText("BAPERS");

        custTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane2.setViewportView(custTable);

        ViewJobButton.setText("View All Customer Accounts");
        ViewJobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewJobButtonActionPerformed(evt);
            }
        });

        FindJobLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FindJobLabel1.setText("Find All");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(vc);
        vc.setText("All Valued Customers");

        buttonGroup1.add(nc);
        nc.setText("All Non Valued Customers");

        Back.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BAPERS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CustomerAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(FindJobLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(vc)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(UpdateAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nc)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back)))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BAPERS1)
                            .addGap(20, 20, 20)
                            .addComponent(JobsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(286, 286, 286))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewJobButton)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAPERS)
                    .addComponent(CustomerAccountLabel)
                    .addComponent(UpdateAccountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vc)
                    .addComponent(nc)
                    .addComponent(FindJobLabel1)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(Back)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BAPERS1)
                        .addComponent(JobsLabel))
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                    .addComponent(ViewJobButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewJobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewJobButtonActionPerformed
        // TODO add your handling code here:
        fetchAllCust();
        
    }//GEN-LAST:event_ViewJobButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        
       fetchSomeCust();
      
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCustomerAccountReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCustomerAccountReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCustomerAccountReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCustomerAccountReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCustomerAccountReceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BAPERS;
    private javax.swing.JLabel BAPERS1;
    private javax.swing.JButton Back;
    private javax.swing.JLabel CustomerAccountLabel;
    private javax.swing.JLabel FindJobLabel1;
    private javax.swing.JLabel JobsLabel;
    private javax.swing.JLabel UpdateAccountLabel;
    private javax.swing.JButton ViewJobButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable custTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton nc;
    private javax.swing.JButton searchButton;
    private javax.swing.JRadioButton vc;
    // End of variables declaration//GEN-END:variables
}
